# Auto-generated by PyPLone compiler — do not edit manually
# PyPLone: Python-like syntax with C++ pointer support

# ── PyPLone Pointer Runtime ──────────────────────────────────────────────
import ctypes as _ctypes

class _PyPloneHeap:
    """Simulates a C++ style heap for PyPLone pointer semantics."""
    def __init__(self):
        self._store = {}
        self._counter = 1

    def alloc(self, obj):
        """Allocate object, return pointer (integer address)."""
        addr = self._counter
        self._store[addr] = obj
        self._counter += 1
        return addr

    def deref(self, addr):
        """Dereference pointer."""
        if addr is None or addr == 0:
            raise RuntimeError("PyPLone: null pointer dereference")
        if addr not in self._store:
            raise RuntimeError(f"PyPLone: invalid pointer {addr} (use-after-free?)")
        return self._store[addr]

    def free(self, addr):
        """Delete / free pointer."""
        if addr is None or addr == 0:
            raise RuntimeError("PyPLone: cannot delete nullptr")
        if addr not in self._store:
            raise RuntimeError(f"PyPLone: double-free detected at {addr}")
        del self._store[addr]

    def addr_of(self, obj):
        """Get pointer to an existing object (or allocate a new slot)."""
        for k, v in self._store.items():
            if v is obj:
                return k
        return self.alloc(obj)

    def set(self, addr, value):
        """Write value at pointer address."""
        if addr is None or addr == 0:
            raise RuntimeError("PyPLone: write through null pointer")
        self._store[addr] = value

_heap = _PyPloneHeap()
# ─────────────────────────────────────────────────────────────────────────


import sys
class StackNode:
    def __init__(self, data):
        self.data = data
        self.prev: int = None
    

class Stack:
    def __init__(self):
        self.top: int = None
        self.size: int = 0
    
    def push(self, data):
        node: int = _heap.alloc(StackNode(data))
        _heap.deref(node).prev = self.top
        self.top = node
        self.size += 1
    
    def pop(self):
        if self.top == None:
            raise IndexError('pop from empty stack')
        data = _heap.deref(self.top).data
        old: int = self.top
        self.top = _heap.deref(self.top).prev
        _heap.free(old)
        self.size -= 1
        return data
    
    def peek(self):
        if self.top == None:
            raise IndexError('peek on empty stack')
        return _heap.deref(self.top).data
    
    def is_empty(self) -> bool:
        return self.top == None
    
    def __len__(self) -> int:
        return self.size
    
    def to_list(self) -> list:
        result: list = []
        cur: int = self.top
        while cur != None:
            result.append(_heap.deref(cur).data)
            cur = _heap.deref(cur).prev
        return result
    

class DLNode:
    def __init__(self, val: int):
        self.val: int = val
        self.prev: int = None
        self.next: int = None
    

class DoublyLinkedList:
    def __init__(self):
        self.head: int = None
        self.tail: int = None
        self.count: int = 0
    
    def push_back(self, val: int):
        node: int = _heap.alloc(DLNode(val))
        if self.tail == None:
            self.head = node
            self.tail = node
        else:
            _heap.deref(node).prev = self.tail
            _heap.deref(self.tail).next = node
            self.tail = node
        self.count += 1
    
    def push_front(self, val: int):
        node: int = _heap.alloc(DLNode(val))
        if self.head == None:
            self.head = node
            self.tail = node
        else:
            _heap.deref(node).next = self.head
            _heap.deref(self.head).prev = node
            self.head = node
        self.count += 1
    
    def pop_back(self) -> int:
        if self.tail == None:
            raise IndexError('pop from empty list')
        val: int = _heap.deref(self.tail).val
        old: int = self.tail
        self.tail = _heap.deref(self.tail).prev
        if self.tail != None:
            _heap.deref(self.tail).next = None
        else:
            self.head = None
        _heap.free(old)
        self.count -= 1
        return val
    
    def forward(self) -> list:
        result: list = []
        cur: int = self.head
        while cur != None:
            result.append(_heap.deref(cur).val)
            cur = _heap.deref(cur).next
        return result
    
    def backward(self) -> list:
        result: list = []
        cur: int = self.tail
        while cur != None:
            result.append(_heap.deref(cur).val)
            cur = _heap.deref(cur).prev
        return result
    

class MinHeap:
    def __init__(self):
        self.data: list = []
    
    def push(self, val: int):
        self.data.append(val)
        self._bubble_up((len(self.data) - 1))
    
    def pop(self) -> int:
        if (notself.data):
            raise IndexError('pop from empty heap')
        root: int = self.data[0]
        last: int = self.data.pop()
        if self.data:
            self.data[0] = last
            self._sink_down(0)
        return root
    
    def _bubble_up(self, i: int):
        while i > 0:
            parent: int = ((i - 1) // 2)
            if self.data[i] < self.data[parent]:
                (self.data[i], self.data[parent]) = (self.data[parent], self.data[i])
                i = parent
            else:
                break
    
    def _sink_down(self, i: int):
        n: int = len(self.data)
        while True:
            smallest: int = i
            left: int = ((2 * i) + 1)
            right: int = ((2 * i) + 2)
            if left < n and self.data[left] < self.data[smallest]:
                smallest = left
            if right < n and self.data[right] < self.data[smallest]:
                smallest = right
            if smallest != i:
                (self.data[i], self.data[smallest]) = (self.data[smallest], self.data[i])
                i = smallest
            else:
                break
    
    def peek(self) -> int:
        return self.data[0]
    
    def __len__(self) -> int:
        return len(self.data)
    

def test_stack():
    print('=== Stack (pointer-linked) ===')
    s = Stack()
    for i in [10, 20, 30, 40, 50]:
        s.push(i)
    print(f"""  Stack: {s.to_list()}""")
    print(f"""  Size:  {len(s)}""")
    print(f"""  Peek:  {s.peek()}""")
    popped: list = []
    while (nots.is_empty()):
        popped.append(s.pop())
    print(f"""  Popped (LIFO): {popped}""")
    print(f"""  Empty: {s.is_empty()}""")

def test_doubly_linked():
    print('\n=== Doubly-Linked List ===')
    dll = DoublyLinkedList()
    for v in [1, 2, 3, 4, 5]:
        dll.push_back(v)
    dll.push_front(0)
    print(f"""  Forward:  {dll.forward()}""")
    print(f"""  Backward: {dll.backward()}""")
    print(f"""  Count:    {dll.count}""")
    dll.pop_back()
    dll.pop_back()
    print(f"""  After 2 pops: {dll.forward()}""")

def test_heap():
    print('\n=== Min-Heap ===')
    h = MinHeap()
    values: list = [5, 3, 8, 1, 9, 2, 7, 4, 6]
    for v in values:
        h.push(v)
    print(f"""  Inserted: {values}""")
    sorted_vals: list = []
    while len(h) > 0:
        sorted_vals.append(h.pop())
    print(f"""  Heap-sorted: {sorted_vals}""")

def test_ptr_arithmetic():
    print('\n=== Raw Pointer Operations ===')
    x: int = 100
    y: int = 200
    p: int = _heap.addr_of(x)
    q: int = _heap.addr_of(y)
    print(f"""  x={x}, y={y}""")
    print(f"""  *p={_heap.deref(p)}, *q={_heap.deref(q)}""")
    print(f"""  p==q: {p == q}""")
    tmp: int = _heap.deref(p)
    heap_tmp: int = _heap.alloc(int(*q))
    print(f"""  heap_tmp value: {_heap.deref(heap_tmp)}""")
    _heap.free(heap_tmp)
    print('  delete heap_tmp — OK')

def main():
    print('╔════════════════════════════════════════════╗')
    print('║  PyPLone Advanced Pointer Tests            ║')
    print('╚════════════════════════════════════════════╝\n')
    test_stack()
    test_doubly_linked()
    test_heap()
    test_ptr_arithmetic()
    print('\n✓ All pointer tests passed!')

main()