# ./Compiler/codegen.py
"""
PyPLone Code Generator
Transpiles PyPLone AST → Python 3.x executable code

Pointer semantics are emulated via a lightweight PyPLone runtime:
  - ptr<T>    → Python type hint (cosmetic)
  - new T()   → __pyplone_heap__ allocation (dict-based)
  - &x        → address (integer ID) into heap
  - *p        → dereference heap ID
  - delete p  → remove from heap
  - x->field  → deref then getattr
  - nullptr   → None
"""

from ast_nodes import *


INDENT = "    "


class CodegenError(Exception):
    pass


class Codegen:
    def __init__(self):
        self.output = []
        self.indent = 0
        self.runtime_needed = False

    def emit(self, line=""):
        self.output.append(INDENT * self.indent + line)

    def emit_raw(self, line=""):
        self.output.append(line)

    def indent_in(self):
        self.indent += 1

    def indent_out(self):
        self.indent -= 1

    def generate(self, module: Module) -> str:
        """Generate full Python source from Module node."""
        # First pass: check if pointer runtime is needed
        self.runtime_needed = self._needs_runtime(module)

        lines = []
        lines.append("# Auto-generated by PyPLone compiler — do not edit manually")
        lines.append("# PyPLone: Python-like syntax with C++ pointer support")
        lines.append("")

        if self.runtime_needed:
            lines += self._runtime_code()
            lines.append("")

        # Generate module body
        for stmt in module.body:
            self.gen_stmt(stmt)

        return "\n".join(lines) + "\n" + "\n".join(self.output)

    def _needs_runtime(self, node) -> bool:
        """Recursively check if pointer operations are used."""
        if isinstance(node, (NewExpr, AddressOf, Deref, DeletePtr, NullPtr)):
            return True
        if isinstance(node, Attribute) and node.is_ptr_access:
            return True
        for val in vars(node).values():
            if isinstance(val, Node) and self._needs_runtime(val):
                return True
            if isinstance(val, list):
                for item in val:
                    if isinstance(item, Node) and self._needs_runtime(item):
                        return True
        return False

    def _runtime_code(self) -> list[str]:
        return [
            "# ── PyPLone Pointer Runtime ──────────────────────────────────────────────",
            "import ctypes as _ctypes",
            "",
            "class _PyPloneHeap:",
            '    """Simulates a C++ style heap for PyPLone pointer semantics."""',
            "    def __init__(self):",
            "        self._store = {}",
            "        self._counter = 1",
            "",
            "    def alloc(self, obj):",
            '        """Allocate object, return pointer (integer address)."""',
            "        addr = self._counter",
            "        self._store[addr] = obj",
            "        self._counter += 1",
            "        return addr",
            "",
            "    def deref(self, addr):",
            '        """Dereference pointer."""',
            "        if addr is None or addr == 0:",
            '            raise RuntimeError("PyPLone: null pointer dereference")',
            "        if addr not in self._store:",
            '            raise RuntimeError(f"PyPLone: invalid pointer {addr} (use-after-free?)")',
            "        return self._store[addr]",
            "",
            "    def free(self, addr):",
            '        """Delete / free pointer."""',
            "        if addr is None or addr == 0:",
            '            raise RuntimeError("PyPLone: cannot delete nullptr")',
            "        if addr not in self._store:",
            '            raise RuntimeError(f"PyPLone: double-free detected at {addr}")',
            "        del self._store[addr]",
            "",
            "    def addr_of(self, obj):",
            '        """Get pointer to an existing object (or allocate a new slot)."""',
            "        for k, v in self._store.items():",
            "            if v is obj:",
            "                return k",
            "        return self.alloc(obj)",
            "",
            "    def set(self, addr, value):",
            '        """Write value at pointer address."""',
            "        if addr is None or addr == 0:",
            '            raise RuntimeError("PyPLone: write through null pointer")',
            "        self._store[addr] = value",
            "",
            "_heap = _PyPloneHeap()",
            "# ─────────────────────────────────────────────────────────────────────────",
            "",
        ]

    # ─── Statements ──────────────────────────────────────────────────────────

    def gen_stmt(self, stmt):
        if stmt is None:
            return
        method = f"gen_{type(stmt).__name__}"
        fn = getattr(self, method, None)
        if fn is None:
            raise CodegenError(f"No codegen for {type(stmt).__name__}")
        fn(stmt)

    def gen_Module(self, node: Module):
        for stmt in node.body:
            self.gen_stmt(stmt)

    def gen_FunctionDef(self, node: FunctionDef):
        for dec in node.decorators:
            self.emit(f"@{self.gen_expr(dec)}")
        params = []
        for p in node.params:
            part = p.name
            if p.annotation:
                part += f": {self.gen_type(p.annotation)}"
            if p.default:
                part += f" = {self.gen_expr(p.default)}"
            params.append(part)
        ret = ""
        if node.return_type:
            ret = f" -> {self.gen_type(node.return_type)}"
        prefix = "async " if node.is_async else ""
        self.emit(f'{prefix}def {node.name}({", ".join(params)}){ret}:')
        self.indent_in()
        if not node.body:
            self.emit("pass")
        else:
            for stmt in node.body:
                self.gen_stmt(stmt)
        self.indent_out()
        self.emit()

    def gen_ClassDef(self, node: ClassDef):
        for dec in node.decorators:
            self.emit(f"@{self.gen_expr(dec)}")
        bases = ", ".join(self.gen_expr(b) for b in node.bases)
        base_str = f"({bases})" if bases else ""
        self.emit(f"class {node.name}{base_str}:")
        self.indent_in()
        if not node.body:
            self.emit("pass")
        else:
            for stmt in node.body:
                self.gen_stmt(stmt)
        self.indent_out()
        self.emit()

    def gen_Return(self, node: Return):
        if node.value is not None:
            self.emit(f"return {self.gen_expr(node.value)}")
        else:
            self.emit("return")

    def gen_Assign(self, node: Assign):
        targets = " = ".join(self.gen_expr(t) for t in node.targets)
        self.emit(f"{targets} = {self.gen_expr(node.value)}")

    def gen_AugAssign(self, node: AugAssign):
        self.emit(f"{self.gen_expr(node.target)} {node.op} {self.gen_expr(node.value)}")

    def gen_AnnAssign(self, node: AnnAssign):
        ann = self.gen_type(node.annotation)
        if node.value is not None:
            self.emit(
                f"{self.gen_expr(node.target)}: {ann} = {self.gen_expr(node.value)}"
            )
        else:
            self.emit(f"{self.gen_expr(node.target)}: {ann}")

    def gen_If(self, node: If):
        self.emit(f"if {self.gen_expr(node.test)}:")
        self.indent_in()
        if not node.body:
            self.emit("pass")
        else:
            for s in node.body:
                self.gen_stmt(s)
        self.indent_out()
        if node.orelse:
            if len(node.orelse) == 1 and isinstance(node.orelse[0], If):
                self.emit(f"elif {self.gen_expr(node.orelse[0].test)}:")
                self.indent_in()
                for s in node.orelse[0].body:
                    self.gen_stmt(s)
                self.indent_out()
                if node.orelse[0].orelse:
                    # Recurse the elif chain
                    fake = If(test=None, body=[], orelse=node.orelse[0].orelse)
                    self._emit_else_chain(fake)
            else:
                self.emit("else:")
                self.indent_in()
                for s in node.orelse:
                    self.gen_stmt(s)
                self.indent_out()

    def _emit_else_chain(self, node: If):
        if node.orelse:
            if len(node.orelse) == 1 and isinstance(node.orelse[0], If):
                inner = node.orelse[0]
                self.emit(f"elif {self.gen_expr(inner.test)}:")
                self.indent_in()
                for s in inner.body:
                    self.gen_stmt(s)
                self.indent_out()
                self._emit_else_chain(inner)
            else:
                self.emit("else:")
                self.indent_in()
                for s in node.orelse:
                    self.gen_stmt(s)
                self.indent_out()

    def gen_While(self, node: While):
        self.emit(f"while {self.gen_expr(node.test)}:")
        self.indent_in()
        if not node.body:
            self.emit("pass")
        else:
            for s in node.body:
                self.gen_stmt(s)
        self.indent_out()

    def gen_For(self, node: For):
        self.emit(f"for {self.gen_expr(node.target)} in {self.gen_expr(node.iter)}:")
        self.indent_in()
        if not node.body:
            self.emit("pass")
        else:
            for s in node.body:
                self.gen_stmt(s)
        self.indent_out()

    def gen_Break(self, node: Break):
        self.emit("break")

    def gen_Continue(self, node: Continue):
        self.emit("continue")

    def gen_Pass(self, node: Pass):
        self.emit("pass")

    def gen_Import(self, node: Import):
        parts = []
        for name, alias in node.names:
            parts.append(f"{name} as {alias}" if alias else name)
        self.emit(f'import {", ".join(parts)}')

    def gen_ImportFrom(self, node: ImportFrom):
        parts = []
        for name, alias in node.names:
            parts.append(f"{name} as {alias}" if alias else name)
        self.emit(f'from {node.module} import {", ".join(parts)}')

    def gen_Try(self, node: Try):
        self.emit("try:")
        self.indent_in()
        for s in node.body or [Pass()]:
            self.gen_stmt(s)
        self.indent_out()
        for h in node.handlers:
            if h.exc_type:
                exc = self.gen_expr(h.exc_type)
                if h.name:
                    self.emit(f"except {exc} as {h.name}:")
                else:
                    self.emit(f"except {exc}:")
            else:
                self.emit("except:")
            self.indent_in()
            for s in h.body or [Pass()]:
                self.gen_stmt(s)
            self.indent_out()
        if node.orelse:
            self.emit("else:")
            self.indent_in()
            for s in node.orelse:
                self.gen_stmt(s)
            self.indent_out()
        if node.finalbody:
            self.emit("finally:")
            self.indent_in()
            for s in node.finalbody:
                self.gen_stmt(s)
            self.indent_out()

    def gen_Raise(self, node: Raise):
        if node.exc:
            self.emit(f"raise {self.gen_expr(node.exc)}")
        else:
            self.emit("raise")

    def gen_Assert(self, node: Assert):
        if node.msg:
            self.emit(f"assert {self.gen_expr(node.test)}, {self.gen_expr(node.msg)}")
        else:
            self.emit(f"assert {self.gen_expr(node.test)}")

    def gen_Delete(self, node: Delete):
        for t in node.targets:
            self.emit(f"del {self.gen_expr(t)}")

    def gen_Global(self, node: Global):
        self.emit(f'global {", ".join(node.names)}')

    def gen_Nonlocal(self, node: Nonlocal):
        self.emit(f'nonlocal {", ".join(node.names)}')

    def gen_Expr(self, node: Expr):
        self.emit(self.gen_expr(node.value))

    def gen_With(self, node: With):
        items = []
        for ctx, var in node.items:
            if var:
                items.append(f"{self.gen_expr(ctx)} as {self.gen_expr(var)}")
            else:
                items.append(self.gen_expr(ctx))
        self.emit(f'with {", ".join(items)}:')
        self.indent_in()
        for s in node.body or [Pass()]:
            self.gen_stmt(s)
        self.indent_out()

    def gen_DeletePtr(self, node: DeletePtr):
        self.emit(f"_heap.free({self.gen_expr(node.target)})")

    def gen_PrintStmt(self, node: PrintStmt):
        args = [self.gen_expr(a) for a in node.args]
        if node.sep is not None:
            args.append(f"sep={self.gen_expr(node.sep)}")
        if node.end is not None:
            args.append(f"end={self.gen_expr(node.end)}")
        self.emit(f'print({", ".join(args)})')

    # ─── Expressions ─────────────────────────────────────────────────────────

    def gen_expr(self, node) -> str:
        if node is None:
            return "None"
        method = f"expr_{type(node).__name__}"
        fn = getattr(self, method, None)
        if fn is None:
            raise CodegenError(f"No expr codegen for {type(node).__name__}")
        return fn(node)

    def gen_type(self, node) -> str:
        """Generate type annotation string."""
        if isinstance(node, PtrType):
            return "int"
        if isinstance(node, Name):
            return node.id
        return self.gen_expr(node)

    def expr_Const(self, node: Const) -> str:
        if isinstance(node.value, str):
            v = node.value
            if v.startswith("f:"):
                # f-string: reconstruct as f"..."
                inner = v[2:]
                # Transform PyPLone pointer ops inside f-string expressions
                import re as _re

                # {*expr} → {_heap.deref(expr)}
                def replace_deref(m):
                    return "{_heap.deref(" + m.group(1) + ")}"

                inner = _re.sub(r"\{\*([^}]+)\}", replace_deref, inner)

                # {expr->attr} → {_heap.deref(expr).attr}
                def replace_arrow(m):
                    return "{_heap.deref(" + m.group(1) + ")" + "." + m.group(2) + "}"

                inner = _re.sub(
                    r"\{([a-zA-Z_][a-zA-Z0-9_]*)\->([a-zA-Z_][a-zA-Z0-9_]*)\}",
                    replace_arrow,
                    inner,
                )
                # Use triple-quote to handle embedded newlines/quotes safely
                if '"""' not in inner:
                    return f'f"""{inner}"""'
                else:
                    return f"f'''{inner}'''"
            return repr(v)
        if node.value is None:
            return "None"
        if isinstance(node.value, bool):
            return "True" if node.value else "False"
        return repr(node.value)

    def expr_Name(self, node: Name) -> str:
        return node.id

    def expr_NullPtr(self, node: NullPtr) -> str:
        return "None"

    def expr_BinOp(self, node: BinOp) -> str:
        l = self.gen_expr(node.left)
        r = self.gen_expr(node.right)
        op = node.op
        if op == "//":
            op = "//"
        return f"({l} {op} {r})"

    def expr_UnaryOp(self, node: UnaryOp) -> str:
        op = node.op
        operand = self.gen_expr(node.operand)
        sep = " " if op.isalpha() else ""
        return f"({op}{sep}{operand})"

    def expr_BoolOp(self, node: BoolOp) -> str:
        parts = [self.gen_expr(v) for v in node.values]
        return f" {node.op} ".join(parts)

    def expr_Compare(self, node: Compare) -> str:
        parts = [self.gen_expr(node.left)]
        for op, comp in zip(node.ops, node.comparators):
            parts.append(op)
            parts.append(self.gen_expr(comp))
        return " ".join(parts)

    def expr_Call(self, node: Call) -> str:
        func = self.gen_expr(node.func)
        args = [self.gen_expr(a) for a in node.args]
        for key, val in node.kwargs:
            if key is None:
                args.append(f"**{self.gen_expr(val)}")
            else:
                args.append(f"{key}={self.gen_expr(val)}")
        return f'{func}({", ".join(args)})'

    def expr_Attribute(self, node: Attribute) -> str:
        obj = self.gen_expr(node.obj)
        if node.is_ptr_access:
            # x->field  →  _heap.deref(x).field
            return f"_heap.deref({obj}).{node.attr}"
        return f"{obj}.{node.attr}"

    def expr_Subscript(self, node: Subscript) -> str:
        obj = self.gen_expr(node.obj)
        idx = self.gen_expr(node.index)
        return f"{obj}[{idx}]"

    def expr_Slice(self, node: Slice) -> str:
        lower = self.gen_expr(node.lower) if node.lower else ""
        upper = self.gen_expr(node.upper) if node.upper else ""
        step = self.gen_expr(node.step) if node.step else ""
        if step:
            return f"{lower}:{upper}:{step}"
        return f"{lower}:{upper}"

    def expr_List(self, node: List) -> str:
        elts = [self.gen_expr(e) for e in node.elts]
        return f'[{", ".join(elts)}]'

    def expr_Tuple(self, node: Tuple) -> str:
        elts = [self.gen_expr(e) for e in node.elts]
        if len(elts) == 1:
            return f"({elts[0]},)"
        return f'({", ".join(elts)})'

    def expr_Dict(self, node: Dict) -> str:
        pairs = [
            f"{self.gen_expr(k)}: {self.gen_expr(v)}"
            for k, v in zip(node.keys, node.values)
        ]
        return "{" + ", ".join(pairs) + "}"

    def expr_Set(self, node: Set) -> str:
        elts = [self.gen_expr(e) for e in node.elts]
        return "{" + ", ".join(elts) + "}"

    def expr_ListComp(self, node: ListComp) -> str:
        elt = self.gen_expr(node.elt)
        gens = self._gen_comprehensions(node.generators)
        return f"[{elt} {gens}]"

    def expr_DictComp(self, node: DictComp) -> str:
        k = self.gen_expr(node.key)
        v = self.gen_expr(node.value)
        gens = self._gen_comprehensions(node.generators)
        return "{" + f"{k}: {v} {gens}" + "}"

    def expr_GeneratorExp(self, node: GeneratorExp) -> str:
        elt = self.gen_expr(node.elt)
        gens = self._gen_comprehensions(node.generators)
        return f"({elt} {gens})"

    def _gen_comprehensions(self, gens) -> str:
        parts = []
        for g in gens:
            part = f"for {self.gen_expr(g.target)} in {self.gen_expr(g.iter)}"
            for cond in g.ifs:
                part += f" if {self.gen_expr(cond)}"
            parts.append(part)
        return " ".join(parts)

    def expr_Lambda(self, node: Lambda) -> str:
        params = ", ".join(p.name for p in node.params)
        body = self.gen_expr(node.body)
        return f"lambda {params}: {body}"

    def expr_IfExp(self, node: IfExp) -> str:
        return f"({self.gen_expr(node.body)} if {self.gen_expr(node.test)} else {self.gen_expr(node.orelse)})"

    def expr_Yield(self, node: Yield) -> str:
        if node.value:
            return f"yield {self.gen_expr(node.value)}"
        return "yield"

    def expr_Await(self, node: Await) -> str:
        return f"await {self.gen_expr(node.value)}"

    def expr_Starred(self, node: Starred) -> str:
        return f"*{self.gen_expr(node.value)}"

    def expr_WalrusOp(self, node: WalrusOp) -> str:
        return f"({self.gen_expr(node.target)} := {self.gen_expr(node.value)})"

    # ─── Pointer expressions ──────────────────────────────────────────────────

    def expr_AddressOf(self, node: AddressOf) -> str:
        """&x  →  _heap.addr_of(x)"""
        return f"_heap.addr_of({self.gen_expr(node.operand)})"

    def expr_Deref(self, node: Deref) -> str:
        """*p  →  _heap.deref(p)"""
        return f"_heap.deref({self.gen_expr(node.operand)})"

    def expr_NewExpr(self, node: NewExpr) -> str:
        """new T(args)  →  _heap.alloc(T(args))"""
        args = ", ".join(self.gen_expr(a) for a in node.args)
        return f"_heap.alloc({node.type_name}({args}))"

    def expr_PtrType(self, node: PtrType) -> str:
        """ptr<T>  →  int (annotated comment)"""
        return "int"
